version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
        POSTGRES_DB: app
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'